import React from 'react';

const Glazuta = () => {
  return (
    <p>
 Leta 1871 je bila zgrajena "glažutarska" cerkvica Sv. Leopolda v Loki pri Žusmu, ki je s svojo notranjo opremo pravi muzej steklarstva. O lepoti steklenih izdelkov iz loške steklarne še vedno pričajo lestenci, ki krasijo številne cerkve na območju Kozjanskega.
Steklarstvo na Kozjanskem ima podobno kot na Pohorju in še marsikje v Sloveniji upoštevanja vredno tradicijo. Razvilo se je predvsem tam, kjer so velike gozdne površine ponujale zadostne količine lesa. Les je bil seveda nepogrešljiv kot kurivo, prav tako pa so iz njega pridobivali pepeliko, ki je poleg kremenčevega peska pri proizvodnji stekla predstavljala eno osnovnih surovin. Steklarne so pogosto ustanavljali zemljiški gospodje, ki so dajali v zakup določene površine gozdov in ko je proizvodnja porabila odobrene zaloge lesa, so se obrati selili na nove lokacije ali pa celo opustili proizvodnjo. Takšne gozdne steklarne ali glažute (iz nemškega die Glashütte) so se pri nas pojavile že sredi 17. stoletja. Najstarejše so nastale na območju Maclja pri Žetalah (takšna je izpričana v pogodbi iz leta 1665), kasneje pa tudi na območju Žičke kartuzije, gospoščine Kozje (Drachenburg) in Svetlega dola pod Svetino, ki so začele z delom sredi 18. stoletja. Na steklarsko zgodovino tega prostora nas spominjajo tudi številna ledinska imena.
Bogastvo proizvodnje steklenih izdelkov je močno zaznamovalo območje nekdanje gospoščine Žusem, kjer se prvi steklar omenja leta 1739. Obstoj glažut je izpričan v jožefinskem in franciscejskem katastru.
Johann Friedrich, lastnik glažute Sveti Jurij ob Taboru v gospostvu Ojstrica, je 24. junija 1836 prosil za dovoljenje, da postavi glažuto v kraju Loka (Laak) v okrožju Žusem. V vlogi je zapisal, da so na tem območju pred tem delovale že tri steklarne. Po prejetju dovoljenja jo je postavil ob potoku Žamerk, voda pa je poganjala tudi brusilni mlin in dva drobilca proda. Kremenčev pesek so dobivali iz Ligista pri Voitsbergu in pri Unterdrauburgu najverjetneje na soboškem območju (Soboth na avstrijskem Štajerskem). Sklenil je tudi pogodbo o sečnji lesa z grofom Harbuval Chamarom; pogodba je bila vknjižena v zemljiško knjigo 6. februarja 1837. Po njej je bilo dovoljeno letno posekati v gozdovih žusemske gospoščine kar 85.000 klafter lesa, kar je pomenilo letno 1.062 klafter cepljenih drv ter dodatno še 195 klafter v gozdu v Vodolah.
Steklarno je dokončno zgradil Joseph Gotscher, ki je prišel iz okolice Haide na severnem Češkem in začel s proizvodnjo leta 1839. Leta 1845 se je Joseph Gotscher glede sečnje lesa zapletel v sodni spor z lastnikom gospoščine Adolfom Ritterjem. Spor je dosegel celo dvorno pisarno na Dunaju in bil dokončno rešen šele s prihodom steklarskega mojstra Leopolda Fiegelmüllerja, ki je v Loko prišel iz Gornje Avstrije in leta 1860 /61 prevzel tako gospoščino kot tudi steklarno. V njegovi, bratovi (Leopold) in lasti njegovega sina (Leopold Fiegelmüller ml.) je steklarna delovala do leta 1886, ko je podlegla konkurenci in ugasnila peči.
Steklarna v Loki je bila v začetku 60. let 19. stoletja tretja največja steklarna na Štajerskem in je podobno kot njene ostale sodobnice v tem času izdelovala poleg steklenic za slatino še steklovino za shranjevanje zdravil in živil, pivsko posodje, svetila, stekleno servirno in jedilno posodo, steklo za šipe in lestence, od katerih nekateri še danes krasijo cerkve na Kozjanskem. Dragocenejše izdelke so krasili z rezanjem, brušenjem in graviranjem, predmeti za vsakdanjo rabo pa so bili v prvi vrsti oblikovno podrejeni svoji funkciji; bili so estetsko preprostih, gladkih - in kljub temu še danes občudovanja vrednih oblik.
    </p>
  )
};

export default Glazuta;